version: "3"

services:
  dotnetdiscordbot:
    build: .
    container_name: discordbot
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    networks:
      - discord
    depends_on:
      - lavalink
      - mysql
    volumes:
      - ./DiscordBot/Config.cs:/app/Config.cs:ro
      - ./DiscordBot/playlists.json:/app/playlists.json:rw
  
  lavalink:
    image: fredboat/lavalink:4.0
    container_name: music-lavalink
    hostname: lavalink
    ports:
      - ${LAVALINK_PORT}:${LAVALINK_PORT}
    restart: unless-stopped
    networks: 
      - discord
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
  
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    hostname: mysql
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
    command:
      - --innodb-buffer-pool-size=1G
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-log-file-size=1G
      - --max-allowed-packet=100M
    volumes:
      - mysqlvolume:/var/lib/mysql
    restart: unless-stopped
    networks:
      - discord
        
networks:
  discord:
