//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Resource.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to queue.
        /// </summary>
        internal static string addedQueue {
            get {
                return ResourceManager.GetString("addedQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no queue.
        /// </summary>
        internal static string ErrorNotQueue {
            get {
                return ResourceManager.GetString("ErrorNotQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to join a voice channel first!.
        /// </summary>
        internal static string NotInChannel {
            get {
                return ResourceManager.GetString("NotInChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be in the same channel as {0}.
        /// </summary>
        internal static string NotInSameChannel {
            get {
                return ResourceManager.GetString("NotInSameChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NowPlaing.
        /// </summary>
        internal static string NowPlaying {
            get {
                return ResourceManager.GetString("NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays audio from YouTube.
        /// </summary>
        internal static string play_Description {
            get {
                return ResourceManager.GetString("play_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0}play YouTube URL or Video Name.
        /// </summary>
        internal static string play_Usage {
            get {
                return ResourceManager.GetString("play_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in queue.
        /// </summary>
        internal static string positionInQueue {
            get {
                return ResourceManager.GetString("positionInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0}remove &lt;Queue Number&gt;.
        /// </summary>
        internal static string remove_Usage {
            get {
                return ResourceManager.GetString("remove_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By.
        /// </summary>
        internal static string RequestedBy {
            get {
                return ResourceManager.GetString("RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0}seek &lt;number h/m/s&gt; Example - {0}seek 2m 10s.
        /// </summary>
        internal static string seek_Usage {
            get {
                return ResourceManager.GetString("seek_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Length.
        /// </summary>
        internal static string TotalLength {
            get {
                return ResourceManager.GetString("TotalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Songs.
        /// </summary>
        internal static string TotalSongs {
            get {
                return ResourceManager.GetString("TotalSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Next.
        /// </summary>
        internal static string UpNext {
            get {
                return ResourceManager.GetString("UpNext", resourceCulture);
            }
        }
    }
}
