lavalink:
  plugins:
    - dependency: dev.lavalink.youtube:youtube-plugin:4e1af561a9316893724aa69eeef623863c04e655
      snapshot: true
  pluginsDir: ./plugins
  server:
    bufferDurationMs: 400
    filters:
      channelMix: true
      distortion: true
      equalizer: true
      karaoke: true
      lowPass: true
      rotation: true
      timescale: true
      tremolo: true
      vibrato: true
      volume: true
    frameBufferDurationMs: 5000
    gc-warnings: true
    nonAllocatingFrameBuffer: false
    opusEncodingQuality: 10
    password: youshallnotpass
    playerUpdateInterval: 5
    resamplingQuality: LOW
    soundcloudSearchEnabled: true
    sources:
      bandcamp: true
      http: true
      local: false
      nico: true
      soundcloud: true
      twitch: true
      vimeo: true
      youtube: false
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubeConfig:
      email: your account mail
      password: your account password
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
logging:
  file:
    max-history: 5
    max-size: 10MB
    path: ./logs/
  level:
    com.github.topi314.lavasrc.LavaSrcTools: "OFF"
    com.sedmelluq.discord.lavaplayer.source.youtube.YoutubePersistentHttpStream: "OFF"
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: "OFF"
    com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream: "OFF"
    dev.lavalink.youtube.YoutubeAudioSourceManager: "OFF"
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
    lavalink: INFO
    lavalink.server.io.SocketContext: "OFF"
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includePayload: true
    includeQueryString: true
    maxPayloadLength: 10000
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
plugins:
  dunctebot:
    sources:
      clypit: true
      getyarn: true
      mixcloud: true
      ocremix: true
      pixeldrain: true
      pornhub: true
      reddit: true
      soundgasm: true
      tiktok: true
      tts: true
    ttsLanguage: en-US
  lavalyrics:
    sources:
      - spotify
      - youtube
      - deezer
      - yandexMusic
  lavasrc:
    applemusic:
      albumLoadLimit: 6
      countryCode: US
      keyID: your key id
      mediaAPIToken: your apple music api token
      musicKitKey: |
        -----BEGIN PRIVATE KEY-----
        your key
        -----END PRIVATE KEY-----
      playlistLoadLimit: 6
      teamID: your team id
    deezer:
      arl: your deezer arl
      formats:
        - FLAC
        - MP3_320
        - MP3_256
        - MP3_128
        - MP3_64
        - AAC_64
      masterDecryptionKey: your master decryption key
    flowerytts:
      audioFormat: mp3
      silence: 0
      speed: 1
      translate: false
      voice: default voice
    jiosaavn:
      decryption:
        secretKey: ??
    lyrics-sources:
      deezer: false
      lrcLib: false
      spotify: false
      vkmusic: false
      yandexmusic: false
      youtube: false
    providers:
      - scsearch:%QUERY%
      - ytsearch:"%ISRC%"
      - ytsearch:%QUERY%
    qobuz:
      userOauthToken: your user oauth token
    sources:
      applemusic: false
      deezer: false
      flowerytts: false
      jiosaavn: false
      qobuz: false
      spotify: false
      tidal: false
      vkmusic: false
      yandexmusic: false
      youtube: true
      ytdlp: false
    spotify:
      albumLoadLimit: 6
      countryCode: US
      customTokenEndpoint: http://localhost:8080/api/token
      localFiles: false
      playlistLoadLimit: 6
      preferAnonymousToken: false
      resolveArtistsInSearch: true
    tidal:
      countryCode: US
      searchLimit: 6
      token: your tidal token
    vkmusic:
      artistLoadLimit: 1
      playlistLoadLimit: 1
      recommendationsLoadLimit: 10
      userToken: your user token
    yandexmusic:
      accessToken: your access token
      albumLoadLimit: 1
      artistLoadLimit: 1
      playlistLoadLimit: 1
    youtube:
      countryCode: US
      language: en
    ytdlp:
      path: yt-dlp
      searchLimit: 10
  youtube:
    allowDirectPlaylistIds: true
    allowDirectVideoIds: true
    allowSearch: true
    clientOptions:
      ANDROID_MUSIC:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      ANDROID_VR:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      IOS:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      MUSIC:
        playback: false
        playlistLoading: false
        searching: true
        videoLoading: false
      MWEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      TV:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: false
      TVHTML5EMBEDDED:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      WEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      WEBEMBEDDED:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
    clients:
      - TV
      - TVHTML5EMBEDDED
      - WEB
      - MWEB
      - WEBEMBEDDED
      - MUSIC
      - ANDROID_VR
      - ANDROID_MUSIC
      - IOS
      - ANDROID
    enabled: true
    oauth:
      enabled: false
sentry:
  dsn: ""
  environment: ""
server:
  address: 0.0.0.0
  http2:
    enabled: false
  port: 9919
