name: release build
on: 
  push:
    branches: ['release']
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: build bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        script: | 
          bash run.sh
